[package]
name = "token-perf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "token-perf"
path = "src/main.rs"

[dependencies]
token-perf-core.workspace = true
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
rust-i18n = "4.2.1"
